apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapps-ns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - pullRequest:
        github:
          # The GitHub organization or user.
          owner: adamyodinsky
          # The Github repository
          repo: app-ephemeraltest
          # For GitHub Enterprise (optional)
          # api: https://git.example.com/
          # Reference to a Secret containing an access token. (optional)
          # tokenRef:
          #   secretName: github-token
          #   key: token
          # Labels is used to filter the PRs that you want to target. (optional)
          # labels:
          # - preview
        requeueAfterSeconds: 20
  template:
    metadata:
      name: "sampleapp-{{branch}}-{{number}}"
      # namespace: 'myapp-{{branch}}-{{number}}-namespace'
    spec:
      source:
        repoURL: "https://github.com/adamyodinsky/app-ephemeraltest.git"
        targetRevision: "{{head_sha}}"
        path: charts/sampleapp
        helm:
          parameters:
            - name: "image.tag"
              value: "pull-{{head_sha}}"
            - name: "environment"
              value: "PR-Namespace-Dev"
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "sampleapp-{{branch}}-{{number}}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
